// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BlazorApp2ML.Model
{
    public class ModelInput
    {
        [ColumnName("Container"), LoadColumn(0)]
        public string Container { get; set; }


        [ColumnName("Data"), LoadColumn(1)]
        public string Data { get; set; }


    }
}
